# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WWEutility
                                 A QGIS plugin
 Plugin to simplify tasks at Westwind
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-12
        copyright            : (C) 2019 by T Clifton
        email                : tclifton3330@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WWEutility class from file WWEutility.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .utility_main import UtilityMain
    return UtilityMain(iface)
