# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerImporter
                                 A QGIS plugin
 Plugin to import the latest version of layers already existing in a workspace
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-12-17
        copyright            : (C) 2018 by T Clifton
        email                : tclifton3330@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerImporter class from file LayerImporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_importer import LayerImporter
    return LayerImporter(iface)
